    version: '3'
    services:
      postgres:
        image: postgres
        restart: always
        environment:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          PGDATA: /var/lib/postgresql/data
        volumes:
          - postgres_data:/var/lib/postgresql/data
        ports:
          - '0.0.0.0:5432:5432'
    
      pgadmin4:
        image: elestio/pgadmin
        restart: always
        environment:
          PGADMIN_DEFAULT_EMAIL: admin@email.com
          PGADMIN_DEFAULT_PASSWORD: 123456
          PGADMIN_LISTEN_PORT: 8080
        ports:
          - '0.0.0.0:8081:8080'
        volumes:
          - ./servers.json:/pgadmin4/servers.json
    
    volumes:
      postgres_data: